# Generated by Django 4.0.4 on 2022-05-18 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DaneProduktu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=150)),
                ('URL_OLX', models.URLField()),
                ('URL_CENEO', models.URLField()),
                ('URL_VINTED', models.URLField()),
                ('SCD', models.IntegerField()),
            ],
        ),
    ]
